package com.zim.organization.presentation.rest;

import com.zim.organization.application.command.RegisterOrganizationCommand;
import com.zim.organization.application.exception.OrganizationAlreadyExistsException;
import com.zim.organization.application.handler.RegisterOrganizationHandler;
import com.zim.organization.application.result.RegisterOrganizationResult;
import com.zim.organization.domain.valueobject.CurrencyCode;
import com.zim.organization.domain.valueobject.OrganizationId;
import com.zim.organization.domain.valueobject.StoreId;
import com.zim.organization.presentation.rest.exception.ApiExceptionHandler;
import com.zim.organization.presentation.rest.request.RegisterOrganizationRequest;
import com.zim.organization.testing.DefaultLocaleExtension;
import com.zim.organization.testing.InMemoryDomainEventPublisher;
import com.zim.organization.testing.InMemoryOrganizationRepository;
import com.zim.organization.testing.LocaleScenario;
import com.zim.shared.domain.TenantId;
import com.zim.shared.tenant.CurrentTenantProvider;
import com.zim.shared.tenant.TenantNotResolvedException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.junit.jupiter.params.provider.NullSource;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;
import org.springframework.context.annotation.Import;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.MediaType;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.ResultActions;

import java.lang.reflect.RecordComponent;
import java.time.Instant;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.aMapWithSize;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@WebMvcTest(OrganizationController.class)
// The test application does not component-scan, so the web slice has to be
// imported explicitly.
@Import({OrganizationController.class, ApiExceptionHandler.class})
@ExtendWith(DefaultLocaleExtension.class)
class OrganizationControllerTest {

  private static final UUID ORGANIZATION_ID =
      UUID.fromString(
          "5c80d578-83f7-4b44-b5f7-598530067a09"
      );

  private static final UUID TENANT_ID =
      UUID.fromString(
          "2d3a7d37-ef2c-4794-b248-b08acf42eb38"
      );

  private static final UUID HEADQUARTERS_ID =
      UUID.fromString(
          "4ee0d038-4617-435c-b7c8-48697d4cf909"
      );

  private static final UUID OTHER_TENANT_ID =
      UUID.fromString(
          "9a4c2e71-5b3d-4f8a-b6c1-0d2e4f6a8b13"
      );

  private static final UUID GENERATED_TENANT_ID =
      UUID.fromString(
          "71e3b0c4-2a9d-4c5e-8f1b-3d6a9e2c4b57"
      );

  private static final Instant CREATED_AT =
      Instant.parse("2026-08-25T10:00:00Z");

  @Autowired
  private MockMvc mockMvc;

  @MockitoBean
  private RegisterOrganizationHandler registerOrganizationHandler;

  /**
   * Fail-closed stub: any endpoint that consults the current tenant gets
   * TenantNotResolvedException. Registration must never consult it.
   */
  @MockitoBean
  private CurrentTenantProvider currentTenantProvider;

  @BeforeEach
  void failClosedTenantProvider() {
    when(currentTenantProvider.currentTenant())
        .thenThrow(new TenantNotResolvedException());
  }

  @Test
  void shouldRegisterWithoutConsultingTheTenantProvider() throws Exception {
    when(registerOrganizationHandler.handle(any())).thenReturn(
        new RegisterOrganizationResult(
            ORGANIZATION_ID,
            TENANT_ID,
            "Quincaillerie Thiès",
            "PENDING_ACTIVATION",
            HEADQUARTERS_ID,
            CREATED_AT
        )
    );

    register(validRequestWith("legalName", "Quincaillerie Thiès SARL"))
        .andExpect(status().isCreated())
        .andExpect(jsonPath("$.tenantId").value(TENANT_ID.toString()));

    verifyNoInteractions(currentTenantProvider);
  }

  /**
   * The tenant of a new organization is generated by the platform. A
   * tenantId in the body or a tenant header supplied by the caller has no
   * effect. The real handler runs behind the mock so that the tenant in
   * the response comes from the generator.
   */
  @Test
  void shouldIgnoreCallerSuppliedTenantOnRegistration() throws Exception {
    RegisterOrganizationHandler realHandler = new RegisterOrganizationHandler(
        new InMemoryOrganizationRepository(),
        () -> new OrganizationId(ORGANIZATION_ID),
        () -> new TenantId(GENERATED_TENANT_ID),
        () -> new StoreId(HEADQUARTERS_ID),
        UUID::randomUUID,
        () -> CREATED_AT,
        new InMemoryDomainEventPublisher()
    );
    when(registerOrganizationHandler.handle(any())).thenAnswer(invocation ->
        realHandler.handle(invocation.getArgument(0))
    );

    String body = """
        {
         "tenantId": "%s",
         "organizationName": "Quincaillerie Thiès",
         "legalName": "Quincaillerie Thiès SARL",
         "currencyCode": "XOF",
         "headquartersCode": "THIES-01",
         "headquartersName": "Magasin principal"
        }
        """.formatted(OTHER_TENANT_ID);

    mockMvc.perform(
            post("/api/organizations")
                .header("X-Tenant-Id", OTHER_TENANT_ID.toString())
                .contentType(MediaType.APPLICATION_JSON)
                .content(body)
        )
        .andExpect(status().isCreated())
        .andExpect(jsonPath("$.tenantId")
            .value(GENERATED_TENANT_ID.toString()));

    verifyNoInteractions(currentTenantProvider);
    assertThat(
        Arrays.stream(RegisterOrganizationRequest.class.getRecordComponents())
            .map(RecordComponent::getName)
    ).doesNotContain("tenantId");
  }

  @Test
  void shouldRegisterOrganization() throws Exception {
    // Given
    RegisterOrganizationResult result =
        new RegisterOrganizationResult(
            ORGANIZATION_ID,
            TENANT_ID,
            "Quincaillerie Thiès",
            "PENDING_ACTIVATION",
            HEADQUARTERS_ID,
            CREATED_AT
        );

    when(registerOrganizationHandler.handle(any()))
        .thenReturn(result);

    String request = """
        {
         "organizationName": "Quincaillerie Thiès",
         "legalName": "Quincaillerie Thiès SARL",
         "currencyCode": "XOF",
         "headquartersCode": "THIES-01",
         "headquartersName": "Magasin principal"
        }
        """;

    // When / Then
    mockMvc.perform(
            post("/api/organizations")
                .contentType(MediaType.APPLICATION_JSON)
                .content(request)
        )
        .andExpect(status().isCreated())
        .andExpect(
            jsonPath("$.organizationId")
                .value(ORGANIZATION_ID.toString())
        )
        .andExpect(
            jsonPath("$.tenantId")
                .value(TENANT_ID.toString())
        )
        .andExpect(
            jsonPath("$.organizationName")
                .value("Quincaillerie Thiès")
        )
        .andExpect(
            jsonPath("$.status")
                .value("PENDING_ACTIVATION")
        )
        .andExpect(
            jsonPath("$.headquartersId")
                .value(HEADQUARTERS_ID.toString())
        )
        .andExpect(
            jsonPath("$.createdAt")
                .value(CREATED_AT.toString())
        );

    verify(registerOrganizationHandler)
        .handle(any());
  }
  /**
   * Every field is invalid; the message pins every part, sorted by field
   * name then text (AC12), whatever the locale.
   */
  @ParameterizedTest
  @MethodSource("nonEnglishLocales")
  void shouldReturnBadRequestWhenRegistrationRequestIsInvalid(
      LocaleScenario locale
  ) throws Exception {
    locale.activate();

    String request = """
      {
       "organizationName": "",
       "legalName": "",
       "currencyCode": "XO",
       "headquartersCode": "",
       "headquartersName": ""
      }
      """;

    register(locale, request)
        .andExpect(status().isBadRequest())
        .andExpect(jsonPath("$", aMapWithSize(3)))
        .andExpect(jsonPath("$.code").value("VALIDATION_FAILED"))
        .andExpect(jsonPath("$.message").value(
            "currencyCode: size must be between 3 and 3; "
                + "headquartersCode: must match the required format; "
                + "headquartersCode: must not be blank; "
                + "headquartersName: must not be blank; "
                + "headquartersName: size must be between 2 and 120; "
                + "legalName: must not be blank; "
                + "legalName: size must be between 2 and 160; "
                + "organizationName: must not be blank; "
                + "organizationName: size must be between 2 and 120"
        ));

    verify(
        registerOrganizationHandler,
        org.mockito.Mockito.never()
    ).handle(any());
  }

  @Test
  void shouldReturnConflictWhenLegalNameAlreadyExists()
      throws Exception {

    when(registerOrganizationHandler.handle(any()))
        .thenThrow(
            new OrganizationAlreadyExistsException(
                "Quincaillerie Thiès SARL"
            )
        );

    String request = """
      {
       "organizationName": "Quincaillerie Thiès",
       "legalName": "Quincaillerie Thiès SARL",
       "currencyCode": "XOF",
       "headquartersCode": "THIES-01",
       "headquartersName": "Magasin principal"
      }
      """;

    mockMvc.perform(
            post("/api/organizations")
                .contentType(MediaType.APPLICATION_JSON)
                .content(request)
        )
        .andExpect(status().isConflict())
        .andExpect(
            jsonPath("$.code")
                .value("ORGANIZATION_ALREADY_EXISTS")
        )
        .andExpect(
            jsonPath("$.message")
                .value(
                    "An organization with legal name "
                        + "'Quincaillerie Thiès SARL' "
                        + "already exists"
                )
        );
  }

  @ParameterizedTest
  @MethodSource("invalidFieldsInNonEnglishLocales")
  void shouldReturnBadRequestWhenFieldDoesNotMatchDomainFormat(
      LocaleScenario locale,
      String field,
      String value,
      String expectedMessage
  ) throws Exception {
    locale.activate();

    register(locale, validRequestWith(field, value))
        .andExpect(status().isBadRequest())
        .andExpect(jsonPath("$", aMapWithSize(3)))
        .andExpect(jsonPath("$.code").value("VALIDATION_FAILED"))
        .andExpect(jsonPath("$.message").value(expectedMessage))
        .andExpect(jsonPath("$.timestamp").exists());

    verify(registerOrganizationHandler, org.mockito.Mockito.never())
        .handle(any());
  }

  /**
   * The {@code @Size} bounds are never formatted with the default locale:
   * under ar-EG, {@code String.format} would print Arabic-Indic digits.
   */
  @ParameterizedTest
  @NullSource
  @ValueSource(strings = "ar-EG")
  void shouldRenderSizeBoundsWithAsciiDigitsUnderArabicLocale(
      String acceptLanguage
  ) throws Exception {
    LocaleScenario locale =
        new LocaleScenario(LocaleScenario.ARABIC_EGYPT, acceptLanguage);
    locale.activate();

    register(locale, validRequestWith("legalName", "Y"))
        .andExpect(status().isBadRequest())
        .andExpect(jsonPath("$.code").value("VALIDATION_FAILED"))
        .andExpect(jsonPath("$.message")
            .value("legalName: size must be between 2 and 160"));
  }

  @ParameterizedTest
  @ValueSource(strings = {"GBP", "ABC"})
  void shouldReturnUnprocessableEntityWhenCurrencyIsNotSupported(
      String currencyCode
  ) throws Exception {
    // The handler builds the real value object, as the production one does
    when(registerOrganizationHandler.handle(any())).thenAnswer(invocation -> {
      RegisterOrganizationCommand command = invocation.getArgument(0);
      new CurrencyCode(command.currencyCode());
      return null;
    });

    register(validRequestWith("currencyCode", currencyCode))
        .andExpect(status().isUnprocessableContent())
        .andExpect(jsonPath("$.code").value("UNSUPPORTED_CURRENCY"));
  }

  /**
   * Malformed JSON never reaches bean validation: it is mapped to the same
   * 400 VALIDATION_FAILED shape, without echoing the parser's message.
   */
  @Test
  void shouldReturnBadRequestWhenRegistrationBodyIsMalformed()
      throws Exception {
    String body = register("{\"organizationName\": \"Quincaillerie Thiès\",")
        .andExpect(status().isBadRequest())
        .andExpect(jsonPath("$", aMapWithSize(3)))
        .andExpect(jsonPath("$.code").value("VALIDATION_FAILED"))
        .andExpect(jsonPath("$.message")
            .value("Request body is missing or malformed"))
        .andExpect(jsonPath("$.timestamp").exists())
        .andReturn().getResponse().getContentAsString();

    assertThat(body).doesNotContain("Quincaillerie");
    verifyNoInteractions(registerOrganizationHandler);
    verifyNoInteractions(currentTenantProvider);
  }

  @Test
  void shouldReturnConflictWithoutSqlDetailsOnDataIntegrityViolation()
      throws Exception {
    when(registerOrganizationHandler.handle(any())).thenThrow(
        new DataIntegrityViolationException(
            "duplicate key value violates unique constraint \"secret\""
        )
    );

    register(validRequestWith("legalName", "Quincaillerie Thiès SARL"))
        .andExpect(status().isConflict())
        .andExpect(jsonPath("$.code").value("DATA_INTEGRITY_VIOLATION"))
        .andExpect(jsonPath("$.message")
            .value("The request conflicts with existing data"));
  }

  private ResultActions register(String body) throws Exception {
    return mockMvc.perform(
        post("/api/organizations")
            .contentType(MediaType.APPLICATION_JSON)
            .content(body)
    );
  }

  private ResultActions register(LocaleScenario locale, String body)
      throws Exception {
    return mockMvc.perform(locale.applyTo(
        post("/api/organizations")
            .contentType(MediaType.APPLICATION_JSON)
            .content(body)
    ));
  }

  static List<LocaleScenario> nonEnglishLocales() {
    return LocaleScenario.nonEnglish();
  }

  /** The Exact messages table of T5f, for the register request. */
  static Stream<Arguments> invalidFieldsInNonEnglishLocales() {
    return LocaleScenario.crossNonEnglish(Stream.of(
        Arguments.of("headquartersCode", "A",
            "headquartersCode: must match the required format"),
        Arguments.of("headquartersCode", "THIES 01",
            "headquartersCode: must match the required format"),
        Arguments.of("organizationName", "X",
            "organizationName: size must be between 2 and 120"),
        Arguments.of("legalName", "Y",
            "legalName: size must be between 2 and 160"),
        Arguments.of("headquartersName", "Z",
            "headquartersName: size must be between 2 and 120"),
        Arguments.of("currencyCode", "XO",
            "currencyCode: size must be between 3 and 3"),
        Arguments.of("currencyCode", "XOFF",
            "currencyCode: size must be between 3 and 3"),
        Arguments.of("organizationName", "   ",
            "organizationName: must not be blank"),
        Arguments.of("legalName", "   ",
            "legalName: must not be blank"),
        Arguments.of("currencyCode", "   ",
            "currencyCode: must not be blank"),
        Arguments.of("headquartersName", "   ",
            "headquartersName: must not be blank"),
        Arguments.of("headquartersCode", "   ",
            "headquartersCode: must match the required format; "
                + "headquartersCode: must not be blank")
    ));
  }

  private static String validRequestWith(String field, String value) {
    Map<String, String> fields = new LinkedHashMap<>();
    fields.put("organizationName", "Quincaillerie Thiès");
    fields.put("legalName", "Quincaillerie Thiès SARL");
    fields.put("currencyCode", "XOF");
    fields.put("headquartersCode", "THIES-01");
    fields.put("headquartersName", "Magasin principal");
    fields.put(field, value);

    return fields.entrySet()
        .stream()
        .map(entry -> "\"%s\": \"%s\"".formatted(
            entry.getKey(),
            entry.getValue()
        ))
        .collect(Collectors.joining(", ", "{", "}"));
  }
}
